# Welcome to Jekyll!

# Website settings
title: "Akanksha Maurya"
description: "Personal website of Akanksha Maurya."
keywords: "akanksha,maurya"
baseurl: "/"
url: "https://mauryaakanksha.github.io"

# author
author:
  name: 'Akanksha'
  first_name: 'Akanksha'
  last_name: 'Maurya'
  email: 'amaurya@ucsd.edu'
  github_username: 'mauryaakanksha'
  linkedin_username: 'akanksha-maurya'
  head_img: 'static/img/landing/Akanksha.jpg'
  desc: 'My description.'

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
