# Welcome to Jekyll!

# Website settings
title: "Akanksha Maurya"
description: "Personal website of Akanksha Maurya."
keywords: "akanksha,maurya"
baseurl: "/"
url: "https://mauryaakanksha.github.io"

# author
author:
  name: 'Akanksha'
  first_name: 'Akanksha'
  last_name: 'Maurya'
  email: 'amaurya@ucsd.edu'
  github_username: 'mauryaakanksha'
  linkedin_username: 'akanksha-maurya'
  head_img: 'static/img/landing/Akanksha.jpg'
  desc: 'I am a Master Student in Computer Engineering at Univeristy of California San Diego. I am working on machine learning in Internet of Things (IoT) applications with Prof. Tajana Rosing at SEE Lab, UCSD. Previously, I worked at Synopsys for 3 years as a Software Engineer where I developed several static verification features for enhancement projects with key customers. I did my undergraduate studies from Indian Institute of Technology Kharagpur in Instrumentation Engineering.'

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
